#pid /tmp/nginx.pid;

events {}

http {

    include /data/data/com.termux/files/usr/etc/nginx/mime.types;

    #access_log /dev/stdout;
    #error_log /dev/stderr;

    server {
        listen 8080;
        root /data/data/com.termux/files/home/francocurotto.com;
        index index.shtml index.html;
        ssi on;
    }
}
