events {}

http {

    include /data/data/com.termux/files/usr/etc/nginx/mime.types;

    server {
        listen 8080;
        root content;
        index index.shtml index.html;
        ssi on;
    }
}
