pid /tmp/nginx.pid;

events {}

http {

    include /etc/nginx/mime.types;

    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 8080;
        root content;
        index index.shtml index.html;
        ssi on;
	location / {
	    try_files $uri $uri.html $uri.shtml $uri/ =404;
	}
    }
}
